// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package db

import (
	"context"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, synopsis, release_year)
VALUES ($1, $2, $3)
RETURNING id, title, synopsis, release_year, created_at, updated_at
`

type CreateMovieParams struct {
	Title       string
	Synopsis    string
	ReleaseYear int32
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie, arg.Title, arg.Synopsis, arg.ReleaseYear)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleaseYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, synopsis, release_year, created_at, updated_at
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleaseYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, synopsis, release_year, created_at, updated_at
FROM movies
ORDER BY id
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Synopsis,
			&i.ReleaseYear,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title = $2,
    synopsis = $3,
    release_year = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, synopsis, release_year, created_at, updated_at
`

type UpdateMovieParams struct {
	ID          int64
	Title       string
	Synopsis    string
	ReleaseYear int32
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Synopsis,
		arg.ReleaseYear,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Synopsis,
		&i.ReleaseYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
