// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
)

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (movie_id, reviewer_name, rating, content)
VALUES ($1, $2, $3, $4)
RETURNING id, movie_id, reviewer_name, rating, content, created_at, updated_at
`

type CreateReviewParams struct {
	MovieID      int64
	ReviewerName string
	Rating       int32
	Content      string
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.MovieID,
		arg.ReviewerName,
		arg.Rating,
		arg.Content,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.ReviewerName,
		&i.Rating,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const getReview = `-- name: GetReview :one
SELECT id, movie_id, reviewer_name, rating, content, created_at, updated_at
FROM reviews
WHERE id = $1
`

func (q *Queries) GetReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.ReviewerName,
		&i.Rating,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReviewsByMovie = `-- name: ListReviewsByMovie :many
SELECT id, movie_id, reviewer_name, rating, content, created_at, updated_at
FROM reviews
WHERE movie_id = $1
ORDER BY id
`

func (q *Queries) ListReviewsByMovie(ctx context.Context, movieID int64) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Review
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.ReviewerName,
			&i.Rating,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReview = `-- name: UpdateReview :one
UPDATE reviews
SET reviewer_name = $2,
    rating = $3,
    content = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, movie_id, reviewer_name, rating, content, created_at, updated_at
`

type UpdateReviewParams struct {
	ID           int64
	ReviewerName string
	Rating       int32
	Content      string
}

func (q *Queries) UpdateReview(ctx context.Context, arg UpdateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReview,
		arg.ID,
		arg.ReviewerName,
		arg.Rating,
		arg.Content,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.ReviewerName,
		&i.Rating,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
